### PR TITLE
Add mesh file for combustor example

### PR DESCRIPTION
**Pull request by ansjsia**
Adding the mesh file for the Fluent tutorial "Chapter 15: Modeling Species Transport and Gaseous Combustion" to create a PyFluent example from it.

### CODE REVIEW

**Comment by raph-luc** [comment]
Can we work with a compressed `.msh.h5` file rather than this plain text `.msh`? Would save a bit of space on the repo

**Comment by ansjsia** [comment]
@raph-luc I figured it should be OK since the mesh is only 90 KB?

**Comment by raph-luc** [comment]
It is OK, as I said: would save "a bit" of space :) 

And this is currently a large plain text file with 5000+ lines, I don't know if this could slow down searches or not. 

Is there any reason not to use the compressed format? 

Fluent Meshing doesn't even let me save a plain text `.msh` file by default:
image

**Comment by ansjsia** [comment]
@raph-luc Good point on slowing down searches. Would you know how to convert it to `.msh.h5` if it's a 2D mesh?

**Review by raph-luc — APPROVED** [review]

**Pull request merged**
