### PR TITLE
Update interference_gui.ui

### PR DESCRIPTION
**Pull request by jsalant22**
add warning label

@myoung301

### CODE REVIEW

**Comment by myoung301** [comment]
@maxcapodi78 Can this file be moved to pyaedt? It's XML defining the UI of the example. One can't really change the example code and this file independently. It's also text and not particularly large. Maybe there is rationale for keeping it here, but if not, it seems like an unnecessary maintenance burden to have it in a separate repo.

CC @jsalant22

**Comment by jsalant22** [comment]
@myoung301 I think the issue is the example doc generator (sphinx?) tries running every file in the examples directory, even non-scripts and this doesn't really make sense in the emit_core directory.

**Review by myoung301 — APPROVED** [review]

**Comment by maxcapodi78** [comment]
If the file is gonna been used from more than an example then I would say yes. But if this file is explicitily made for that example then I would rater use example_data repos to host it.
________________________________
Da: Matthew Young ***@***.***>
Inviato: mercoledì 13 settembre 2023 16:18
A: ansys/example-data ***@***.***>
Cc: Massimo Capodiferro ***@***.***>; Mention ***@***.***>
Oggetto: Re: [ansys/example-data] Update interference_gui.ui (PR #188)


[External Sender]

@maxcapodi78<https://github.com/maxcapodi78> Can this file be moved to pyaedt? It's XML defining the UI of the example. One can't really change the example code and this file independently. It's also text and not particularly large. Maybe there is rationale for keeping it here, but if not, it seems like an unnecessary maintenance burden to have it in a separate repo.

CC @jsalant22<https://github.com/jsalant22>

**Comment by jsalant22** [comment]
@maxcapodi78 Can you review/merge this? Thanks

**Review by MaxJPRey — APPROVED** [review]
LGTM.

**Pull request merged**
